auth page fixes
FifthTry/ui pull request #6
Opened 2023-12-26 07:12 UTC by MeenuKumari28

review fixes for auth page

2023-12-26 07:50 UTC, yashveer29 requested changes
Ui Reviews:-
1. Increase the "fifthtry slides" logo size
2. "Do not have acc" is broken fix the font
3. Change the button colour to white.

The default language should be English.

2023-12-26 10:00 UTC, Arpita-Jaiswal approved these changes

2023-12-28 07:23 UTC, amitu approved these changes

2023-12-28 07:23 UTC, amitu commented
Waiting for @yashveer29's approval.

2023-12-28 07:27 UTC, yashveer29 approved these changes

2023-12-28 10:16 UTC, merged